[package]
name = "examples"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = "0.11"
bevy_motiongfx = {version="0.1", path="../bevy_motiongfx"}

[[example]]
name = "hello_world"
path = "hello_world.rs"

[[example]]
name = "easings"
path = "easings.rs"
