[package]
name = "motiongfx_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = { version = "0.13", default-features = false }
bevy_ecs = { version = "0.13", default-features = false }
bevy_math = { version = "0.13", default-features = false }
bevy_render = { version = "0.13", default-features = false }
bevy_time = { version = "0.13", default-features = false }
bevy_utils = { version = "0.13", default-features = false }
bevy_vello_renderer = { git = "https://github.com/nixon-voxell/bevy_vello_renderer", rev = "2d93b863c40e2bfd7349f9f3b122b7be440faeba" }
smallvec = "1.11"
